// <auto-generated />
using MicroservicesRebus.Estoque.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MicroservicesRebus.Estoque.Api.Migrations
{
    [DbContext(typeof(EstoqueContext))]
    [Migration("20200320030939_CriarBancoDados")]
    partial class CriarBancoDados
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MicroservicesRebus.Estoque.Api.Model.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("nome")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<int>("QuantidadeEstoque")
                        .HasColumnName("quantidadeEstoque")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnName("valor")
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("Id");

                    b.ToTable("produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "BMW X1",
                            QuantidadeEstoque = 100,
                            Valor = 200000m
                        },
                        new
                        {
                            Id = 2,
                            Nome = "BMW 320",
                            QuantidadeEstoque = 100,
                            Valor = 250000m
                        },
                        new
                        {
                            Id = 3,
                            Nome = "MERCEDES A200",
                            QuantidadeEstoque = 100,
                            Valor = 290000m
                        },
                        new
                        {
                            Id = 4,
                            Nome = "LAND EVOQUE",
                            QuantidadeEstoque = 100,
                            Valor = 350000m
                        },
                        new
                        {
                            Id = 5,
                            Nome = "FERRARI F40",
                            QuantidadeEstoque = 100,
                            Valor = 1250000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
