// <auto-generated />
using System;
using MicroservicesRebus.Pedido.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MicroservicesRebus.Pedido.Api.Migrations
{
    [DbContext(typeof(PedidoContext))]
    partial class PedidoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MicroservicesRebus.Pedido.Api.Model.ItemPedido", b =>
                {
                    b.Property<int>("NumeroPedido")
                        .HasColumnName("numero_pedido")
                        .HasColumnType("int");

                    b.Property<int>("ProdutoID")
                        .HasColumnName("produto_id")
                        .HasColumnType("int");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasColumnName("nome_produto")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<int>("Quantidade")
                        .HasColumnName("quantidade")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnName("valor_unitario")
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("NumeroPedido", "ProdutoID");

                    b.ToTable("pedidos_itens");
                });

            modelBuilder.Entity("MicroservicesRebus.Pedido.Api.Model.Pedido", b =>
                {
                    b.Property<int>("Numero")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("numero")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnName("data")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MotivoCancelamento")
                        .HasColumnName("motivo_cancelamento")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnName("nome_cliente")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<short>("Status")
                        .HasColumnName("status")
                        .HasColumnType("smallint");

                    b.HasKey("Numero");

                    b.ToTable("pedidos");
                });

            modelBuilder.Entity("MicroservicesRebus.Pedido.Api.Model.ItemPedido", b =>
                {
                    b.HasOne("MicroservicesRebus.Pedido.Api.Model.Pedido", null)
                        .WithMany("Itens")
                        .HasForeignKey("NumeroPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
